# -*- coding: utf-8 -*-
"""Welcome to Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#e22cseu1059
#krishna kansal
#import libraries and resizing the image
import cv2
from google.colab.patches import cv2_imshow
image_path="/content/download.jpeg";
img=cv2.imread(image_path)
imgresize=cv2.resize(img,(300,300))
cv2_imshow(imgresize)

#converting the image into grayscale and resizing it
gray_img=cv2.imread(image_path,0)
gray_img_resize=cv2.resize(gray_img,(300,300))
cv2_imshow(gray_img_resize)

#applying the average function (blur) on the gray image
kernel_size=(5,5)
blur_img=cv2.blur(gray_img_resize,kernel_size)
blur_img_resize=cv2.resize(blur_img,(300,300))
cv2_imshow(blur_img_resize)

from google.colab.patches import cv2_imshow
image_path="/content/download.jpeg";
img=cv2.imread(image_path)
imgresize=cv2.resize(img,(300,300))
cv2_imshow(imgresize)

import matplotlib.pyplot as plt

# Calculate the histogram
hist = cv2.calcHist([gray_img], [0], None, [256], [0, 256])

# Plot the histogram
plt.figure()
plt.title("Grayscale Histogram")
plt.xlabel("Bins")
plt.ylabel("Number of Pixels")
plt.plot(hist)
plt.xlim([0, 256])
plt.show()

colors = ('b', 'g', 'r')
plt.figure(figsize=(6, 4))
for i, color in enumerate(colors):
    hist_rgb = cv2.calcHist([img], [i], None, [256], [0, 256])
    plt.plot(hist_rgb, color=color)
plt.title('RGB Histogram')
plt.xlabel('Pixel Intensity')
plt.ylabel('Frequency')

plt.legend(colors)
plt.show()